### PR TITLE
Regi sign in

### PR DESCRIPTION
**Pull request by skim-93**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Test A
- [ ] Test B

**Test Configuration**:
* Firmware version:
* Hardware:
* Toolchain:
* SDK:

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by skim-93** [comment]
I rearragned the folders a bit, please review and merge this!

**Comment by gtullio12** [comment]
Please review commit structure before making a pull request. When reading your git commit message I have no idea what changes were implemented. Also for pull request the changes to commits need to be atomic, as in one commit = one change. There are many many changes in just one commit making it very difficult to understand what changes were made. As someone doing a code review I have no idea what changes were made. Also the pull request template was not filled out. Here are Taehong and mines pull request, so you can have a template of what is expected. 
https://github.com/gtullio12/Team-1-TCSS-450-Webservice/pull/1
https://github.com/gtullio12/Team-1-TCSS-450/pull/71

Can you please redo the pull request but with atomic commits so I can see exactly what changes are being made.

**Comment by skim-93** [comment]
Sure, Should I try to make another branch and implement it again one by one? or is there any way that I can make atomic commits for the ones I already pushed to the branch?

**Comment by gtullio12** [comment]
Yeah I would advise making a new branch from master and doing each individual change and commiting. If you need help I would be happy to help. Im not sure on how to do the commit structure with the Github desktop tool though.

**Comment by gtullio12** [comment]
Since Taehong did it, he could probably assist better

**Comment by taehong3** [comment]
> Since Taehong did it, better

**Comment by taehong3** [comment]
Some minor things, I think we didn't follow naming convention for string
ex: <Where>_<Description>  // I also didn't follow that rule, so we may need to update it in next pull request.
Other than, I think it looks good.

**Comment by skim-93** [comment]
I will redo the commit, with atomic commits.

**Pull request closed without merging**
